{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.1-fix/mockative-3.0.1-fix.module",
    "group": "io.mockative",
    "module": "mockative",
    "version": "3.0.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative.klib",
          "url": "mockative-watchosx64-3.0.1-fix.klib",
          "size": 116227,
          "sha512": "adcd008ca1b6f0ba5458e34a6f7f01d51424cf867176bedf3ae89009b0720f1c7bd118747f4b45245470dc31ca75a0afe4d73b9584d097aac0d63f75e73e78fd",
          "sha256": "0036db5129b0185f77cdadbe892098c52ea2f65eef1fb15c4c4c5aa1033c99e3",
          "sha1": "e74c9721b3a427bca15afaf0e5fba99acfe929ce",
          "md5": "3acd5f8a2a4281a9eeab10ed5c3a1c11"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-watchosx64-3.0.1-fix-sources.jar",
          "url": "mockative-watchosx64-3.0.1-fix-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-watchosx64-3.0.1-fix-metadata.jar",
          "url": "mockative-watchosx64-3.0.1-fix-metadata.jar",
          "size": 261,
          "sha512": "5d6d60e57c4fa6c2a57ab94efeb95d4b81e5fe4a0ebae99ec2136886e7f7b245283077ab6520cff3b74834f2cb6dcebf78f8a7b2c96cae5e7a74278d97aa7dc5",
          "sha256": "45cab7ed34f5790ab8f97b7f08ef10c10f506ea595c4a19b0c56f7f4abc9fd51",
          "sha1": "82ff2ed71d651d72e8837bfd97b2ef8fa51a2b99",
          "md5": "3be64687e57b9572e62295d9a37fe99c"
        }
      ]
    }
  ]
}
