{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.1-fix/mockative-3.0.1-fix.module",
    "group": "io.mockative",
    "module": "mockative",
    "version": "3.0.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative.klib",
          "url": "mockative-mingwx64-3.0.1-fix.klib",
          "size": 116210,
          "sha512": "8331896ddf760c23059d0d9f6cc58be02ced6224ec24812c98e1966a8ffcbc7663b094a37c24a49bb142e149bf1a0dc16627c2dea2f2d097a4fec850ef56f2a8",
          "sha256": "74965e4177ae815e59333657550f491692c3f19ee07f2af8efb92c58c21c4bfc",
          "sha1": "b04cd855c884fac6f976a62b9e0c8bc30d35378c",
          "md5": "8185436309b1642c152aa3f923c3970e"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-mingwx64-3.0.1-fix-sources.jar",
          "url": "mockative-mingwx64-3.0.1-fix-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    }
  ]
}
