{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.1-fix/mockative-3.0.1-fix.module",
    "group": "io.mockative",
    "module": "mockative",
    "version": "3.0.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-wasm-js-3.0.1-fix.klib",
          "url": "mockative-wasm-js-3.0.1-fix.klib",
          "size": 114131,
          "sha512": "454fc4254f03198dc0e7aa13048463270dd317041ea9839797afad7d787fe0090d90b2f22bc0cd5d9cb8bf3d690c953b10b0f7b06ce7f0eb9f780e9f8d7408b2",
          "sha256": "b8369dddd4ddf2e6eced3453a7908045857fa7ed60cb2aec8b6f35dc8034deca",
          "sha1": "3edc693b7af9bcd7b87d565b7f99dec94f5d5cc4",
          "md5": "f40389bb5cb11139f57a00d1f6e138a9"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-wasm-js-3.0.1-fix.klib",
          "url": "mockative-wasm-js-3.0.1-fix.klib",
          "size": 114131,
          "sha512": "454fc4254f03198dc0e7aa13048463270dd317041ea9839797afad7d787fe0090d90b2f22bc0cd5d9cb8bf3d690c953b10b0f7b06ce7f0eb9f780e9f8d7408b2",
          "sha256": "b8369dddd4ddf2e6eced3453a7908045857fa7ed60cb2aec8b6f35dc8034deca",
          "sha1": "3edc693b7af9bcd7b87d565b7f99dec94f5d5cc4",
          "md5": "f40389bb5cb11139f57a00d1f6e138a9"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "mockative-wasm-js-3.0.1-fix-sources.jar",
          "url": "mockative-wasm-js-3.0.1-fix-sources.jar",
          "size": 26574,
          "sha512": "72553ab268c38398a3193437f9b2afa5b1b5c6a4493470eb6019bb24516a855dc2999cd0000447f6ade7c6f4b8cfb9948336b9b84d6ef11d5f516432d1bdb777",
          "sha256": "cbb0287d5f56fabe427b66377cd04b40daf1eec9524c624037751c5b8c779c80",
          "sha1": "bcf943966b13e930daf3fe34019bd116143e917c",
          "md5": "65d06c570b1f830d2d4a65d4cde19a34"
        }
      ]
    }
  ]
}
