{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockative/3.0.1-fix/mockative-3.0.1-fix.module",
    "group": "io.mockative",
    "module": "mockative",
    "version": "3.0.1-fix",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative.klib",
          "url": "mockative-watchosarm64-3.0.1-fix.klib",
          "size": 116244,
          "sha512": "7f670a9edb3f6be3955a7233991dc546d09382ed05b213761bc30f719cbfe2ca0b078cb616272df8619cddd2609b71f64a293d5111c6beb5c1f1832a0e249971",
          "sha256": "833a01591369550473e2584289b9293fab0d12801c2f6aae5e2657786131b947",
          "sha1": "5645add84c6fedc10d6d27d4c70adb88ff3f26d0",
          "md5": "e6a3d0da1902974f1350cf8631684b0e"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "mockative-watchosarm64-3.0.1-fix-sources.jar",
          "url": "mockative-watchosarm64-3.0.1-fix-sources.jar",
          "size": 26608,
          "sha512": "b4ac6c450e576befb94a4267ed010f07f4c447379b53b1206409fc46e9da80712529caa31744f6925b34e90e042c896316b7ebf78a2497ffe340acfac8ae542f",
          "sha256": "812750547df1ca7a8a74577d621ca69d8960aabb07de4c19716b6e3fca7cbdac",
          "sha1": "ebad7076aef4e9fce66c6dd80426f13ba4b82750",
          "md5": "9e102d1341eb4f34e6ba7981d7cff88d"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "mockative-watchosarm64-3.0.1-fix-metadata.jar",
          "url": "mockative-watchosarm64-3.0.1-fix-metadata.jar",
          "size": 261,
          "sha512": "acc080ec62ae8a6ae2518c8df815c6035b25f388635afbdf374dfbadff0ab51a6ee98b82c59a45aa0c25365a7e4d94a442adb69a89ae0de1a491e444e0f59341",
          "sha256": "5b126bc10223583432983e603eeaa281c9b1aabfef31d6bb962e7d21c6e75c7d",
          "sha1": "95f36630051d4148a6b00d9bb785598535fb9e9f",
          "md5": "4c7bdc4129019ffab8e9eebb0f401c75"
        }
      ]
    }
  ]
}
